apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-05-07T03:27:19Z"
  labels:
    app: rng
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-05-07T03:27:19Z"
  name: rng
  namespace: default
  resourceVersion: "19716"
  selfLink: /api/v1/namespaces/default/services/rng
  uid: 821726f7-ec90-4a68-b175-a0f89e600224
spec:
  clusterIP: 10.109.14.211
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
